<?php
/**
 * Arabic Language File
 */

$lang = [
    // General
    'app_name'          => 'نظام إدارة مهام التصميم',
    'dashboard'         => 'لوحة التحكم',
    'login'             => 'تسجيل الدخول',
    'logout'            => 'تسجيل الخروج',
    'welcome'           => 'مرحباً',
    'save'              => 'حفظ',
    'cancel'            => 'إلغاء',
    'create'            => 'إنشاء',
    'update'            => 'تحديث',
    'delete'            => 'حذف',
    'edit'              => 'تعديل',
    'search'            => 'بحث',
    'filter'            => 'تصفية',
    'reset'             => 'إعادة تعيين',
    'actions'           => 'إجراءات',
    'yes'               => 'نعم',
    'no'                => 'لا',
    'back'              => 'رجوع',
    'submit'            => 'إرسال',
    'loading'           => 'جاري التحميل...',
    'no_data'           => 'لا توجد بيانات',
    'success'           => 'تمت العملية بنجاح',
    'error'             => 'حدث خطأ',
    'confirm_delete'    => 'هل أنت متأكد من الحذف؟',
    'all'               => 'الكل',
    'view'              => 'عرض',
    'details'           => 'التفاصيل',
    'close'             => 'إغلاق',

    // Login Page
    'login_title'       => 'تسجيل الدخول',
    'login_subtitle'    => 'نظام إدارة مهام التصميم',
    'email'             => 'البريد الإلكتروني',
    'password'          => 'كلمة المرور',
    'login_btn'         => 'دخول',
    'login_error'       => 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'login_required'    => 'يرجى تسجيل الدخول للمتابعة',

    // Navigation
    'nav_dashboard'     => 'لوحة التحكم',
    'nav_all_tasks'     => 'جميع المهام',
    'nav_create_task'   => 'إنشاء مهمة',
    'nav_my_tasks'      => 'مهامي',
    'nav_reports'       => 'التقارير',
    'nav_users'         => 'إدارة المستخدمين',
    'nav_settings'      => 'الإعدادات',
    'nav_language'      => 'English',

    // Dashboard
    'total_tasks'       => 'إجمالي المهام',
    'new_tasks'         => 'مهام جديدة',
    'in_progress_tasks' => 'قيد التنفيذ',
    'delivered_tasks'   => 'تم التسليم',
    'recent_tasks'      => 'المهام الأخيرة',
    'quick_actions'     => 'إجراءات سريعة',
    'create_new_task'   => 'إنشاء مهمة جديدة',
    'view_all_tasks'    => 'عرض جميع المهام',
    'view_reports'      => 'عرض التقارير',

    // Tasks
    'task'              => 'مهمة',
    'tasks'             => 'المهام',
    'task_title'        => 'عنوان المهمة',
    'client_name'       => 'اسم العميل',
    'design_type'       => 'نوع التصميم',
    'notes'             => 'ملاحظات / موجز',
    'deadline'          => 'الموعد النهائي',
    'assigned_to'       => 'مسند إلى',
    'assigned_designer' => 'المصمم المسند إليه',
    'progress'          => 'نسبة الإنجاز',
    'status'            => 'الحالة',
    'created_by'        => 'أنشئت بواسطة',
    'created_at'        => 'تاريخ الإنشاء',
    'updated_at'        => 'تاريخ التحديث',
    'task_created'      => 'تم إنشاء المهمة بنجاح',
    'task_updated'      => 'تم تحديث المهمة بنجاح',
    'task_deleted'      => 'تم حذف المهمة بنجاح',
    'select_designer'   => 'اختر المصمم',
    'select_type'       => 'اختر نوع التصميم',
    'select_status'     => 'اختر الحالة',
    'edit_task'         => 'تعديل المهمة',
    'task_details'      => 'تفاصيل المهمة',
    'update_status'     => 'تحديث الحالة',
    'update_progress'   => 'تحديث نسبة الإنجاز',
    'no_tasks'          => 'لا توجد مهام',
    'overdue'           => 'متأخر',
    'due_today'         => 'مستحق اليوم',
    'upcoming'          => 'قادم',

    // Status labels
    'status_new'        => 'جديد',
    'status_in_progress'=> 'قيد التنفيذ',
    'status_delivered'  => 'تم التسليم',

    // Design types
    'type_file'         => 'ملف',
    'type_logo'         => 'شعار',
    'type_design'       => 'تصميم',
    'type_motion_design'=> 'موشن ديزاين',
    'type_profile'      => 'بروفايل',

    // Reports
    'reports'           => 'تقارير الأداء',
    'report_title'      => 'تقرير أداء المصممين',
    'designer_name'     => 'اسم المصمم',
    'total_assigned'    => 'إجمالي المهام المسندة',
    'total_delivered'   => 'إجمالي المسلّمة',
    'total_in_progress' => 'إجمالي قيد التنفيذ',
    'total_new'         => 'إجمالي الجديدة',
    'breakdown_by_type' => 'تفصيل حسب نوع التصميم',
    'filter_by_designer'=> 'تصفية حسب المصمم',
    'filter_by_date'    => 'تصفية حسب التاريخ',
    'filter_by_type'    => 'تصفية حسب نوع التصميم',
    'date_from'         => 'من',
    'date_to'           => 'إلى',
    'apply_filter'      => 'تطبيق',
    'clear_filter'      => 'مسح التصفية',
    'performance_summary' => 'ملخص الأداء',
    'delivery_rate'     => 'نسبة التسليم',

    // User Management
    'users'             => 'المستخدمون',
    'user_management'   => 'إدارة المستخدمين',
    'add_user'          => 'إضافة مستخدم',
    'edit_user'         => 'تعديل المستخدم',
    'full_name'         => 'الاسم الكامل',
    'role'              => 'الدور',
    'role_manager'      => 'مدير',
    'role_designer'     => 'مصمم',
    'role_supervisor'   => 'مشرف',
    'new_password'      => 'كلمة مرور جديدة',
    'leave_blank'       => 'اتركها فارغة للاحتفاظ بكلمة المرور الحالية',
    'user_created'      => 'تم إنشاء المستخدم بنجاح',
    'user_updated'      => 'تم تحديث المستخدم بنجاح',
    'user_deleted'      => 'تم حذف المستخدم بنجاح',
    'select_role'       => 'اختر الدور',
    'confirm_delete_user' => 'هل أنت متأكد من حذف هذا المستخدم؟',
    'cannot_delete_self'  => 'لا يمكنك حذف حسابك الخاص',

    // Validation
    'required_field'    => 'هذا الحقل مطلوب',
    'invalid_email'     => 'يرجى إدخال بريد إلكتروني صحيح',
    'email_exists'      => 'هذا البريد الإلكتروني مسجل بالفعل',
    'password_min'      => 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',

    // File Upload
    'upload_design'     => 'رفع ملفات التصميم',
    'upload_required'   => 'يجب رفع ملف التصميم عند تحويل الحالة إلى تم التسليم',
    'upload_file'       => 'ملف التصميم',
    'upload_success'    => 'تم رفع الملف بنجاح',
    'upload_error'      => 'حدث خطأ أثناء رفع الملف',
    'upload_invalid'    => 'نوع الملف غير مسموح. المسموح: JPG, PNG, GIF, PDF, AI, PSD, SVG, EPS, ZIP, RAR, MP4, MOV, WEBP',
    'upload_too_large'  => 'حجم الملف كبير جداً. الحد الأقصى: 20 ميجابايت',
    'download_file'     => 'تحميل ملف التصميم',
    'design_file'       => 'ملف التصميم',
    'no_file_uploaded'  => 'لم يتم رفع ملف تصميم بعد',
    'view_file'         => 'عرض / تحميل الملف',
    'uploaded_files'    => 'الملفات المرفوعة',
    'upload_hint_multiple' => 'يمكنك اختيار عدة ملفات. المسموح: JPG, PNG, GIF, PDF, AI, PSD, SVG, EPS, ZIP, RAR, MP4, MOV, WEBP (الحد الأقصى 20 ميجا لكل ملف)',

    // Telegram
    'telegram_chat_id'  => 'معرّف تيليجرام (Chat ID)',
    'telegram_hint'     => 'أرسل /start إلى @WavesDesignerbot ثم أدخل معرّف المحادثة هنا',
    'telegram_notified' => 'تم إرسال إشعار تيليجرام',

    // Notifications
    'notifications'         => 'الإشعارات',
    'no_notifications'      => 'لا توجد إشعارات',
    'mark_all_read'         => 'تحديد الكل كمقروء',
    'view_all_notifications'=> 'عرض جميع الإشعارات',
    'just_now'              => 'الآن',
    'minutes_ago'           => 'د',
    'hours_ago'             => 'س',
    'days_ago'              => 'أيام',
    'notif_new_task'        => 'مهمة جديدة مسندة إليك',
    'notif_task_delivered'  => 'تم تسليم المهمة',
    'notif_task_updated'    => 'تم تحديث المهمة',

    // Misc
    'copyright'         => '© 2025 نظام إدارة مهام التصميم. جميع الحقوق محفوظة.',
    'switch_lang'       => 'English',
    'direction'         => 'rtl',
];
