<?php
/**
 * English Language File
 */

$lang = [
    // General
    'app_name'          => 'Design Task Manager',
    'dashboard'         => 'Dashboard',
    'login'             => 'Login',
    'logout'            => 'Logout',
    'welcome'           => 'Welcome',
    'save'              => 'Save',
    'cancel'            => 'Cancel',
    'create'            => 'Create',
    'update'            => 'Update',
    'delete'            => 'Delete',
    'edit'              => 'Edit',
    'search'            => 'Search',
    'filter'            => 'Filter',
    'reset'             => 'Reset',
    'actions'           => 'Actions',
    'yes'               => 'Yes',
    'no'                => 'No',
    'back'              => 'Back',
    'submit'            => 'Submit',
    'loading'           => 'Loading...',
    'no_data'           => 'No data available',
    'success'           => 'Operation completed successfully',
    'error'             => 'An error occurred',
    'confirm_delete'    => 'Are you sure you want to delete this?',
    'all'               => 'All',
    'view'              => 'View',
    'details'           => 'Details',
    'close'             => 'Close',

    // Login Page
    'login_title'       => 'Sign In',
    'login_subtitle'    => 'Design Task Management System',
    'email'             => 'Email',
    'password'          => 'Password',
    'login_btn'         => 'Sign In',
    'login_error'       => 'Invalid email or password',
    'login_required'    => 'Please log in to continue',

    // Navigation
    'nav_dashboard'     => 'Dashboard',
    'nav_all_tasks'     => 'All Tasks',
    'nav_create_task'   => 'Create Task',
    'nav_my_tasks'      => 'My Tasks',
    'nav_reports'       => 'Reports',
    'nav_users'         => 'User Management',
    'nav_settings'      => 'Settings',
    'nav_language'      => 'العربية',

    // Dashboard
    'total_tasks'       => 'Total Tasks',
    'new_tasks'         => 'New Tasks',
    'in_progress_tasks' => 'In Progress',
    'delivered_tasks'   => 'Delivered',
    'recent_tasks'      => 'Recent Tasks',
    'quick_actions'     => 'Quick Actions',
    'create_new_task'   => 'Create New Task',
    'view_all_tasks'    => 'View All Tasks',
    'view_reports'      => 'View Reports',

    // Tasks
    'task'              => 'Task',
    'tasks'             => 'Tasks',
    'task_title'        => 'Task Title',
    'client_name'       => 'Client Name',
    'design_type'       => 'Design Type',
    'notes'             => 'Notes / Brief',
    'deadline'          => 'Deadline',
    'assigned_to'       => 'Assigned To',
    'assigned_designer' => 'Assigned Designer',
    'progress'          => 'Progress',
    'status'            => 'Status',
    'created_by'        => 'Created By',
    'created_at'        => 'Created At',
    'updated_at'        => 'Updated At',
    'task_created'      => 'Task created successfully',
    'task_updated'      => 'Task updated successfully',
    'task_deleted'      => 'Task deleted successfully',
    'select_designer'   => 'Select Designer',
    'select_type'       => 'Select Design Type',
    'select_status'     => 'Select Status',
    'edit_task'         => 'Edit Task',
    'task_details'      => 'Task Details',
    'update_status'     => 'Update Status',
    'update_progress'   => 'Update Progress',
    'no_tasks'          => 'No tasks found',
    'overdue'           => 'Overdue',
    'due_today'         => 'Due Today',
    'upcoming'          => 'Upcoming',

    // Status labels
    'status_new'        => 'New',
    'status_in_progress'=> 'In Progress',
    'status_delivered'  => 'Delivered',

    // Design types
    'type_file'         => 'File',
    'type_logo'         => 'Logo',
    'type_design'       => 'Design',
    'type_motion_design'=> 'Motion Design',
    'type_profile'      => 'Profile',

    // Reports
    'reports'           => 'Performance Reports',
    'report_title'      => 'Designer Performance Report',
    'designer_name'     => 'Designer Name',
    'total_assigned'    => 'Total Assigned',
    'total_delivered'   => 'Total Delivered',
    'total_in_progress' => 'Total In Progress',
    'total_new'         => 'Total New',
    'breakdown_by_type' => 'Breakdown by Design Type',
    'filter_by_designer'=> 'Filter by Designer',
    'filter_by_date'    => 'Filter by Date Range',
    'filter_by_type'    => 'Filter by Design Type',
    'date_from'         => 'From',
    'date_to'           => 'To',
    'apply_filter'      => 'Apply Filter',
    'clear_filter'      => 'Clear Filter',
    'performance_summary' => 'Performance Summary',
    'delivery_rate'     => 'Delivery Rate',

    // User Management
    'users'             => 'Users',
    'user_management'   => 'User Management',
    'add_user'          => 'Add User',
    'edit_user'         => 'Edit User',
    'full_name'         => 'Full Name',
    'role'              => 'Role',
    'role_manager'      => 'Manager',
    'role_designer'     => 'Designer',
    'role_supervisor'   => 'Supervisor',
    'new_password'      => 'New Password',
    'leave_blank'       => 'Leave blank to keep current password',
    'user_created'      => 'User created successfully',
    'user_updated'      => 'User updated successfully',
    'user_deleted'      => 'User deleted successfully',
    'select_role'       => 'Select Role',
    'confirm_delete_user' => 'Are you sure you want to delete this user?',
    'cannot_delete_self'  => 'You cannot delete your own account',

    // Validation
    'required_field'    => 'This field is required',
    'invalid_email'     => 'Please enter a valid email',
    'email_exists'      => 'This email is already registered',
    'password_min'      => 'Password must be at least 6 characters',

    // File Upload
    'upload_design'     => 'Upload Design Files',
    'upload_required'   => 'You must upload the design file when marking as delivered',
    'upload_file'       => 'Design File',
    'upload_success'    => 'File uploaded successfully',
    'upload_error'      => 'Error uploading file',
    'upload_invalid'    => 'Invalid file type. Allowed: JPG, PNG, GIF, PDF, AI, PSD, SVG, EPS, ZIP, RAR, MP4, MOV, WEBP',
    'upload_too_large'  => 'File is too large. Maximum size: 20MB',
    'download_file'     => 'Download Design File',
    'design_file'       => 'Design File',
    'no_file_uploaded'  => 'No design file uploaded yet',
    'view_file'         => 'View / Download File',
    'uploaded_files'    => 'Uploaded Files',
    'upload_hint_multiple' => 'You can select multiple files. Allowed: JPG, PNG, GIF, PDF, AI, PSD, SVG, EPS, ZIP, RAR, MP4, MOV, WEBP (max 20MB each)',

    // Telegram
    'telegram_chat_id'  => 'Telegram Chat ID',
    'telegram_hint'     => 'Send /start to @WavesDesignerbot then enter your Chat ID here',
    'telegram_notified' => 'Telegram notification sent',

    // Notifications
    'notifications'         => 'Notifications',
    'no_notifications'      => 'No notifications',
    'mark_all_read'         => 'Mark all as read',
    'view_all_notifications'=> 'View All Notifications',
    'just_now'              => 'Just now',
    'minutes_ago'           => 'min ago',
    'hours_ago'             => 'hr ago',
    'days_ago'              => 'days ago',
    'notif_new_task'        => 'New task assigned to you',
    'notif_task_delivered'  => 'Task has been delivered',
    'notif_task_updated'    => 'Task has been updated',

    // Misc
    'copyright'         => '© 2025 Design Task Manager. All rights reserved.',
    'switch_lang'       => 'العربية',
    'direction'         => 'ltr',
];
